% Generated by MATLAB(R) 26.1 (R2026a) and Bluetooth Toolbox 26.1 (R2026a).
% Generated on: 14-Jul-2026 17:19:48

%% 正在生成 Bluetooth BR/EDR 波形
% Bluetooth BR/EDR 配置
bluetoothCfg = bluetoothWaveformConfig('Mode', 'EDR2M', ...
    'PacketType', 'FHS', ...
    'LogicalTransportAddress', [0;0;1], ...
    'HeaderControlBits', [1;1;1], ...
    'ModulationIndex', 0.32, ...
    'SamplesPerSymbol', 16, ...
    'WhitenInitialization', [1;1;1;1;1;1;1], ...
    'LLID', [1;1], ...
    'FlowIndicator', true);

bluetoothCfg.PayloadLength = 18;
bluetoothCfg.WhitenStatus = 'Off';
bluetoothCfg.DeviceAddress = '0123456789AB';
% input bit source:
in = randi([1 1],18*8,1);


% 生成
waveform = bluetoothWaveformGenerator(in, bluetoothCfg);
payloadLength = getPayloadLength(bluetoothCfg);
filterSpan = 8*any(strcmp(bluetoothCfg.Mode,{'EDR2M','EDR3M'}));
packetDuration = bluetoothPacketDuration(bluetoothCfg.Mode,bluetoothCfg.PacketType,payloadLength);
waveform = waveform(1:(packetDuration+filterSpan)*bluetoothCfg.SamplesPerSymbol);
waveform = waveform(2016+80+1:(packetDuration+filterSpan)*bluetoothCfg.SamplesPerSymbol)
Fs = 1.6e+07; 								 % 以 Hz 为单位指定波形的采样率


%% 将仿真波形输出为txt文本作为testbench数据输入
Width = 15; %数据位宽
I_n=round(real(waveform)*(2^(Width)-1));
Q_n=round(imag(waveform)*(2^(Width)-1));
fid=fopen('edr2I.txt','w');
for k=1:length(I_n)
    B_s=dec2bin(I_n(k)+((I_n(k))<0)*2^Width,Width);
    for j=1:Width
        if B_s(j)=='1'
            tb=1;
        else
            tb=0;
        end
        fprintf(fid,'%d',tb);
    end
    fprintf(fid,'\r\n');
end
fprintf(fid,';');
fclose(fid);

fid=fopen('edr2Q.txt','w');     
for k=1:length(Q_n)
    B_s=dec2bin(Q_n(k)+((Q_n(k))<0)*2^Width,Width);
    for j=1:Width
        if B_s(j)=='1'
            tb=1;
        else
            tb=0;
        end
        fprintf(fid,'%d',tb);
    end
    fprintf(fid,'\r\n');
end
fprintf(fid,';');
fclose(fid);

if true
%% 可视化
scope = timescope(SampleRate=Fs,...
    TimeSpanSource="property",...
    TimeSpan=1e-5);
scope(waveform)
% Spectrum Analyzer
spectrum = spectrumAnalyzer(SampleRate=Fs, AveragingMethod='exponential', ForgettingFactor=1);
spectrum(waveform);
release(spectrum);

% Constellation Diagram
constel = comm.ConstellationDiagram('ColorFading', true, ...
    'ShowTrajectory', 0, ...
    'ShowReferenceConstellation', false);
constel(waveform);
release(constel);
end

